<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alert with OK  Cancel</name>
   <tag></tag>
   <elementGuidId>4c819711-b96f-47a6-98d5-d4b433b55dea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Alert with OK &amp; Cancel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7ded69d-7c95-43df-b57a-a1e1746b3747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#CancelTab</value>
      <webElementGuid>3add0fe2-7159-4787-b045-9d790b5d6d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>bdd9f2a0-6bd5-41fd-ab5a-e5d1efeacd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>analystic</value>
      <webElementGuid>94fe5269-331e-4f90-b375-59f33185ae70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert with OK &amp; Cancel </value>
      <webElementGuid>d72d8d93-02db-4469-9db0-f01ca823db68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;nav nav-tabs&quot;]/div[@class=&quot;tabpane pullleft&quot;]/ul[@class=&quot;nav nav-tabs nav-stacked&quot;]/li[2]/a[@class=&quot;analystic&quot;]</value>
      <webElementGuid>d71e9f85-1826-4b6d-b7e2-22c9c36acab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alert with OK &amp; Cancel')]</value>
      <webElementGuid>4787f71c-ef2d-4835-b932-5fb018e16678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert with OK'])[1]/following::a[1]</value>
      <webElementGuid>b7f1e894-42e1-47b2-890e-7696cea24162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice Site'])[1]/following::a[2]</value>
      <webElementGuid>fbc933f0-f484-4310-bb86-26e826534088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert with Textbox'])[1]/preceding::a[1]</value>
      <webElementGuid>c41d9c93-523f-4ea3-aa01-d61759198d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert with OK &amp; Cancel']/parent::*</value>
      <webElementGuid>db8af183-8e8b-4832-9aae-6ee49b5bce1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#CancelTab')]</value>
      <webElementGuid>39240c7a-997f-475e-bde3-32273a5952db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]/a</value>
      <webElementGuid>a07fd573-18af-4369-a02f-f4711768196f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#CancelTab' and (text() = 'Alert with OK &amp; Cancel ' or . = 'Alert with OK &amp; Cancel ')]</value>
      <webElementGuid>893fb354-1e93-4d4d-a18b-658786c3a4c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
