<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alert with Textbox</name>
   <tag></tag>
   <elementGuidId>60d59318-6bb4-4e43-9767-994fa36daf90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Alert with Textbox')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>965d9d49-31f2-4dce-a804-ebe1bd293af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Textbox</value>
      <webElementGuid>7e9c88df-6a6d-4dbb-aa76-9a28d24b4732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f69b78a5-8db9-4d11-8d4d-c141dc9886c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>analystic</value>
      <webElementGuid>19926cdc-8fe8-48be-80f9-3bba90ac40d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert with Textbox </value>
      <webElementGuid>fb78fa2e-38b4-4008-82b9-922d95d89794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;nav nav-tabs&quot;]/div[@class=&quot;tabpane pullleft&quot;]/ul[@class=&quot;nav nav-tabs nav-stacked&quot;]/li[3]/a[@class=&quot;analystic&quot;]</value>
      <webElementGuid>3bdc52cb-01df-4e10-b22e-f13ee042f36f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alert with Textbox')]</value>
      <webElementGuid>a7c076b6-92e2-4994-8603-373221734a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert with OK &amp; Cancel'])[1]/following::a[1]</value>
      <webElementGuid>96312383-526a-4484-a4bd-41f7841265f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alert with OK'])[1]/following::a[2]</value>
      <webElementGuid>102ddfe1-d239-4568-a39e-e529ff652f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click the button to display a confirm box'])[1]/preceding::a[1]</value>
      <webElementGuid>70a98c33-0227-477a-8b7e-6fa0269cef76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert with Textbox']/parent::*</value>
      <webElementGuid>81a5b4fa-55f4-4d83-a63e-567abcf9cc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Textbox')]</value>
      <webElementGuid>1e8eb94f-cbcc-4e2f-9abe-490c08f4bf78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/a</value>
      <webElementGuid>4ba23741-aa95-484a-a3df-e79b6e448b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Textbox' and (text() = 'Alert with Textbox ' or . = 'Alert with Textbox ')]</value>
      <webElementGuid>aaa59592-7a8c-4fc2-8935-e5e40cdb15ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
