<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Run_tryhome</name>
   <tag></tag>
   <elementGuidId>47538e83-53ad-44e1-b63c-e296b608124f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tryhome']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tryhome</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13091e47-8fef-4f80-ab12-e8f69fad3dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tryhome</value>
      <webElementGuid>8af4ce50-4904-4b2e-b366-53d2afee296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.w3schools.com</value>
      <webElementGuid>4a8cad0c-e6f2-4133-adcb-3c202953ec68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>24322f04-7f98-4dcc-b62d-79ad13c0ae16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>w3schools.com Home</value>
      <webElementGuid>b46e2512-9b07-4211-b739-a8482263e764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-button w3-bar-item topnav-icons fa fa-home ga-tryit</value>
      <webElementGuid>e9440a1c-3f9c-48ad-bdbb-0b36fd6950db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tryhome&quot;)</value>
      <webElementGuid>d3c05861-7e69-4227-a47a-6ed256bf7044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tryhome']</value>
      <webElementGuid>e66f0c61-90fb-4969-94cb-7eb155e78c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.w3schools.com')]</value>
      <webElementGuid>af82090e-9e23-4abc-b8a9-3fb3c0936f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>77609d3f-8281-47dc-8e1e-1d01be3555d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tryhome' and @href = 'https://www.w3schools.com' and @title = 'w3schools.com Home']</value>
      <webElementGuid>b2446ca2-dc32-4fea-975f-8827356d98e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
