<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook helps you connect and share with the people in your life_passContainer</name>
   <tag></tag>
   <elementGuidId>5662e199-4106-4d35-9009-347d4ee13aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>142364ad-24d1-4b85-958a-a3d3d7cd5330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6luy _55r1 _1kbt</value>
      <webElementGuid>b70913ea-46d4-41e0-b8c4-edbd3207379b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passContainer</value>
      <webElementGuid>bf6bd46f-b3ad-41b6-80d1-2022b7aa04bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passContainer&quot;)</value>
      <webElementGuid>c0c79773-13a9-4775-9df3-69592c462f25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='passContainer']</value>
      <webElementGuid>9dcabc3a-afb7-4c53-9fc3-eaadc50626f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_fz']/div/div[2]/div</value>
      <webElementGuid>d32e3e39-6d47-45d5-ab76-bcab3e79afa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook helps you connect and share with the people in your life.'])[1]/following::div[7]</value>
      <webElementGuid>6c87a652-ba6b-4bf5-a8f0-069dde72d9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[4]</value>
      <webElementGuid>239fcc43-39c6-426e-8d51-dc53b1092c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::div[5]</value>
      <webElementGuid>734718da-09b3-4162-874d-d7133e6a74ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div</value>
      <webElementGuid>bb42aabb-e1aa-4c27-8ce4-d4fbafa40856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'passContainer']</value>
      <webElementGuid>018e0c4c-639d-4ca6-9b85-0d91ae176cb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
