<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Facebook helps you connect and share with the people in your life__6lux</name>
   <tag></tag>
   <elementGuidId>5eda318c-5269-4fd0-8aab-ebf570e0fd1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._6lux</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='u_0_2_fz']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35eda552-95a4-4cd0-909a-61258eb81371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6lux</value>
      <webElementGuid>40bf409a-8419-4482-b1c1-3b5f8d4d91bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_2_fz&quot;)/div[1]/div[@class=&quot;_6lux&quot;]</value>
      <webElementGuid>25ed053e-77ec-4819-9ebd-226e762a92df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_fz']/div/div</value>
      <webElementGuid>12538e63-b25c-4dd8-bed7-68260d73c065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook helps you connect and share with the people in your life.'])[1]/following::div[5]</value>
      <webElementGuid>9b945b87-fb4b-4af5-8cdd-30175e25b9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[6]</value>
      <webElementGuid>e0cd71a9-8bbd-4513-b13d-82285641d614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::div[7]</value>
      <webElementGuid>e49742fe-4a16-4356-bf84-8ca64bd34782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>189f59fd-ac0d-4a44-bd51-2f6a1cce4937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
