<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_pdf-sample1 (9) (1).pdf</name>
   <tag></tag>
   <elementGuidId>127a7722-0c5b-444f-9ddd-b88d3601e722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UploadedInvoicefilesOriginal-unqorkioFileUpload']/table/tbody/tr/td[2]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc06e042-7bfb-4912-bd0e-eb2831cf34ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76107c38-ba20-449a-8ae4-4cca633fe5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e4d776f-f0f7-4b63-bb1e-f140c2f0f18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>download()</value>
      <webElementGuid>b5a16795-751d-4e9a-8ae7-f11ef02ec285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>keyDownHandler($event)</value>
      <webElementGuid>aabdbd91-973d-4042-a9d3-60c392aa0b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>pdf-sample1 (9) (1).pdf</value>
      <webElementGuid>2518be75-a0d4-4dad-8178-03565489dfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>06550bc0-6d00-4b61-9bee-a16692d56d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          pdf-sample1 (9) (1).pdf
        </value>
      <webElementGuid>6e088141-0fc3-4ddd-afea-bfe49abe9a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UploadedInvoicefilesOriginal-unqorkioFileUpload&quot;)/table[@class=&quot;table table-striped table-bordered ng-pristine ng-untouched ng-scope ng-isolate-scope ng-not-empty ng-valid ng-valid-required&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[2]/span[@class=&quot;ng-isolate-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>07a2efe5-a0b8-49f7-90d5-02e4d0dc9645</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UploadedInvoicefilesOriginal-unqorkioFileUpload']/table/tbody/tr/td[2]/span/a</value>
      <webElementGuid>a03dc70f-656c-4bf1-8ee8-1bff01540f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'pdf-sample1 (9) (1).pdf')]</value>
      <webElementGuid>8a7c2ea8-e691-4e3b-82d3-59ec828525fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[2]/following::a[2]</value>
      <webElementGuid>daa4461c-b8ed-4d74-af54-7660b39d3fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File'])[2]/following::a[2]</value>
      <webElementGuid>d6ebf4fe-3469-4f83-ade5-a120f398be31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='browse'])[2]/preceding::a[1]</value>
      <webElementGuid>fdbc6556-6546-4b92-bc10-c4a1374cd3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pdf-sample1 (9) (1).pdf']/parent::*</value>
      <webElementGuid>467cb2b2-f49a-4466-b83c-b1abf5ff1642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>e19cfec6-1093-4eed-be0b-ab67467991d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
          pdf-sample1 (9) (1).pdf
        ' or . = '
          pdf-sample1 (9) (1).pdf
        ')]</value>
      <webElementGuid>ea4d6b63-aae7-400a-ac53-5cc08558a6f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
