<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>browse</name>
   <tag></tag>
   <elementGuidId>ad672c16-f928-44b1-a090-8c2ef80353c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='UploadedInvoicefilesOriginal-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UploadedInvoicefilesOriginal-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fea73b0-8b20-434f-a4da-2269dd7fcfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44cb7344-d8c4-4ccd-a275-d2129a402c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngf-select</name>
      <type>Main</type>
      <value>upload($files, $invalidFiles)</value>
      <webElementGuid>f027f0e1-c035-4afe-b3eb-f6ea60d75be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngf-accept</name>
      <type>Main</type>
      <value>component.filePattern</value>
      <webElementGuid>f9845c9f-976f-4921-a82b-c35dc2d87dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngf-multiple</name>
      <type>Main</type>
      <value>component.multiple</value>
      <webElementGuid>74727b2d-cbfb-4cd5-a0e1-1157ab349c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-link fileSelector__button ng-binding</value>
      <webElementGuid>ff3e0af8-e37b-4869-acaf-692f26129ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>fb2005a1-b30f-4a8f-a88d-6d9a93c1e880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UploadedInvoicefilesOriginal</value>
      <webElementGuid>621aaf65-1b1b-4851-bb97-fadab5dbf796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UploadedInvoicefilesOriginal-button</value>
      <webElementGuid>68871cb8-0081-44ef-be81-b97e1615faa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> browse </value>
      <webElementGuid>336df290-3ca4-424a-9a86-18870a2e4f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UploadedInvoicefilesOriginal-button&quot;)</value>
      <webElementGuid>261254a5-44bc-4103-bde2-a3b0e709c789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='UploadedInvoicefilesOriginal-button']</value>
      <webElementGuid>53322b40-f03b-4333-a2a0-e950cbf839ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UploadedInvoicefilesOriginal']/button</value>
      <webElementGuid>51ca17d9-7249-48da-91e1-77f5b642cafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[2]/following::button[1]</value>
      <webElementGuid>36b43db2-4ccc-4c95-94fa-bf7b574bafa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum allowed file size (each file): MB'])[2]/preceding::button[1]</value>
      <webElementGuid>e26fe177-b813-4e66-86a9-db6bf35ef7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Drag/Drop is not supported for this browser'])[2]/preceding::button[1]</value>
      <webElementGuid>0b2a2093-3bf9-4590-826e-c14cba5b56d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>fcf3f929-819d-4ff8-a98f-d1e86b3aa06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'UploadedInvoicefilesOriginal-button' and (text() = ' browse ' or . = ' browse ')]</value>
      <webElementGuid>ebd63e8e-6452-435a-83e3-2edfd1e80636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
