<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button</name>
   <tag></tag>
   <elementGuidId>56d84b66-837b-42bc-8acd-a021814e8867</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='Upload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.jsgrid-cell.upload > span > button[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf81e9bf-1e5a-4cf5-a676-ea4c27242329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f23057ab-e3c7-488c-b61d-3d50b2354b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>b5f26ebd-6eb2-4e0a-b4d6-6deb07077087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jsGrid_panelMainVg&quot;)/div[@class=&quot;jsgrid-grid-body&quot;]/table[@class=&quot;jsgrid-table&quot;]/tbody[1]/tr[@class=&quot;jsgrid-alt-row&quot;]/td[@class=&quot;jsgrid-cell upload&quot;]/span[1]/button[1]</value>
      <webElementGuid>87d94c75-78e8-4ee3-8534-18811e3ab6bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='Upload']</value>
      <webElementGuid>2d875712-e146-442f-832d-364c03495c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jsGrid_panelMainVg']/div[2]/table/tbody/tr[2]/td[12]/span/button</value>
      <webElementGuid>049a01fb-986f-43b6-a150-cfb5675b1ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/span/button</value>
      <webElementGuid>7d6be156-adfa-4a4c-8605-9877b940b8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>93cf3ead-3a8a-4e60-9e30-f4023df652a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
