<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Original</name>
   <tag></tag>
   <elementGuidId>0ecaa155-94ac-4f30-b7eb-451fbbaedb41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-group-uploadFileType']/div/div[3]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5075f57b-70ed-49d7-9db9-48f4f96d03b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>318248f5-0d13-401b-9eca-76d8f8fa349b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Original</value>
      <webElementGuid>e1aa6abf-5c02-4398-a4a6-71f3fb12a9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-group-uploadFileType&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope radio-inline&quot;]/label[@class=&quot;control-label&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>427719c4-a86a-41af-8f6b-cf64eec56e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-uploadFileType']/div/div[3]/label/span</value>
      <webElementGuid>cae5c325-74fc-4700-91d1-06b87d53908f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proforma'])[1]/following::span[1]</value>
      <webElementGuid>dd1eca32-7b57-4d12-9a5e-85b65eecc59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Type'])[1]/following::span[2]</value>
      <webElementGuid>6f3545bd-d798-49b1-9841-18c81355c809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Type is required'])[1]/preceding::span[1]</value>
      <webElementGuid>331fb87e-856e-460f-97a4-620229a19984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Proforma Invoice'])[1]/preceding::span[1]</value>
      <webElementGuid>4ab35b6b-c29b-4815-bf30-8193863f2d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Original']/parent::*</value>
      <webElementGuid>1f1873ab-39b9-46a0-83c8-2710d8eddd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span</value>
      <webElementGuid>2934c147-108e-475d-9466-22587c8d5d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Original' or . = 'Original')]</value>
      <webElementGuid>e5ddd3cd-4cf1-4516-844d-4a26caed98af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
