<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add User</name>
   <tag></tag>
   <elementGuidId>4e833e71-ed90-47fe-a196-ecb2d46d11a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8c5575b-59bb-48c4-a8a0-abd175e62054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-type</name>
      <type>Main</type>
      <value>{{ getButtonType() }}</value>
      <webElementGuid>dc88dace-cea6-480b-8b43-8665eda658eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddUser</value>
      <webElementGuid>ce6d0ef5-0fd3-4b52-bec6-c2a329469495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAddUser</value>
      <webElementGuid>4db0a94b-5409-48d6-a1d6-4285fa01b713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'btn-block': (component.block === 'true' || component.block === true), 'has-icon': component.leftIcon || component.rightIcon}</value>
      <webElementGuid>73159f8f-34aa-4fb1-acf7-8b676423b90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-md has-icon</value>
      <webElementGuid>6d7eef29-21d9-4cdb-be12-457673eb7496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>component.disabled || (unqorkioForm.submitting &amp;&amp; !component.preventDisableOnSubmitting) || (component.disableOnInvalid &amp;&amp; (currentFormInvalid()||hasErrors()))</value>
      <webElementGuid>e85c252f-8342-44e9-9aba-f12e015df292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$emit('buttonClick', component, componentId)</value>
      <webElementGuid>3215674a-95b7-46c6-ab3e-398742f2a718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad30761f-3671-4d8a-98f7-38fa37a4f14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Add User    </value>
      <webElementGuid>dea0a469-5a20-454a-8a6a-e99e9f2a684d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddUser&quot;)</value>
      <webElementGuid>2a9bdbe3-c05f-43a9-805f-9132665cbc04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddUser']</value>
      <webElementGuid>805fb9ee-f438-472d-968d-8a5aa99f71e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-btnAddUser']/button</value>
      <webElementGuid>6a3b187d-883b-4d5a-bf8e-76899776cb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Kratos User Requests'])[1]/following::button[1]</value>
      <webElementGuid>6b87dbc2-5dfc-4c7e-8ae9-359811d322b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2021 Triterras. All rights reserved'])[6]/following::button[1]</value>
      <webElementGuid>0ff304f6-5dd2-4259-a533-a971ca7eff0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vgUsers'])[1]/preceding::button[1]</value>
      <webElementGuid>2c38b8bc-6c63-49f0-ad73-cce2c88bf04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/button</value>
      <webElementGuid>9d5744e7-7b4b-43c7-9a6c-9273d53bd72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAddUser' and @name = 'btnAddUser' and @type = 'button' and (text() = '    Add User    ' or . = '    Add User    ')]</value>
      <webElementGuid>97b60bc7-c1b0-4df0-a35d-02551d3b40c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
