<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>58022076-853c-4254-af9a-a168b03d7cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddNewUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddNewUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f974068c-e89f-4f8c-8a21-856c16a5ee81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-type</name>
      <type>Main</type>
      <value>{{ getButtonType() }}</value>
      <webElementGuid>97f0799f-49f7-41f9-b570-73a20b1ccb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddNewUser</value>
      <webElementGuid>aca26da0-b253-4fb0-a9d8-acc547fa3459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnAddNewUser</value>
      <webElementGuid>674f1e44-db76-4795-983b-066ad88dc73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'btn-block': (component.block === 'true' || component.block === true), 'has-icon': component.leftIcon || component.rightIcon}</value>
      <webElementGuid>256e4d38-f0f1-482b-be82-6d9a4ffd304f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-md has-icon</value>
      <webElementGuid>dc73f0de-fed5-4b54-87eb-0cc3893e737e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>component.disabled || (unqorkioForm.submitting &amp;&amp; !component.preventDisableOnSubmitting) || (component.disableOnInvalid &amp;&amp; (currentFormInvalid()||hasErrors()))</value>
      <webElementGuid>ad3bcee6-e728-4c83-bce4-fddcc712892d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$emit('buttonClick', component, componentId)</value>
      <webElementGuid>0aee0e2f-69a4-443b-8718-7230561d6624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47b1f1a0-b7b0-46da-836a-5daeb16ee31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Submit     </value>
      <webElementGuid>c420fe3a-43d8-4635-b7f1-8dd6a4641631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddNewUser&quot;)</value>
      <webElementGuid>d9ab2805-db36-4991-971d-9671fb1b8171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddNewUser']</value>
      <webElementGuid>0ccea969-03c2-48e6-997b-8aa6df14ca6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-btnAddNewUser']/button</value>
      <webElementGuid>e4f496f9-de29-4c12-a65c-4d618a9a8155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>13b5ca20-869a-49d3-8fe2-27cc1e77a50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KratosAdminMaker'])[1]/following::button[2]</value>
      <webElementGuid>2ff1ebc9-f6cb-400c-a1d1-efabd203d222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview as:'])[1]/preceding::button[1]</value>
      <webElementGuid>3ce15e29-e327-44cb-a678-94ba1ce566e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/button</value>
      <webElementGuid>6af43592-fb24-40d5-86ec-98cbb5461ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnAddNewUser' and @name = 'btnAddNewUser' and @type = 'button' and (text() = '   Submit     ' or . = '   Submit     ')]</value>
      <webElementGuid>afd4eea6-a7d2-4aae-b63d-d9f831c7b241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
