<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>965db7d7-5e04-4f64-ad08-c35a3efbe4ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addInvoice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addInvoice</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9d9f48e-5040-49cb-b64f-1914a0eeec53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-type</name>
      <type>Main</type>
      <value>{{ getButtonType() }}</value>
      <webElementGuid>b2c0ca9b-1791-489f-9934-d42e7b3b1207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addInvoice</value>
      <webElementGuid>ddf8093d-4fd8-4c17-aad3-cdc5cac1ed7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addInvoice</value>
      <webElementGuid>f4bd0fe0-b438-44ec-9ef4-9266ae1987a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'btn-block': (component.block === 'true' || component.block === true), 'has-icon': component.leftIcon || component.rightIcon}</value>
      <webElementGuid>0e349bf3-505a-4402-8b49-525f72feee82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-md has-icon</value>
      <webElementGuid>be74baae-2cba-4151-97b5-089dcfef42b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>component.disabled || (unqorkioForm.submitting &amp;&amp; !component.preventDisableOnSubmitting) || (component.disableOnInvalid &amp;&amp; (currentFormInvalid()||hasErrors()))</value>
      <webElementGuid>1864ee5e-c09d-4ac1-8fd2-0f0e7a9756bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$emit('buttonClick', component, componentId)</value>
      <webElementGuid>a8dae067-ba85-48d2-8a9a-69a5a595efd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e8b4b9e-0280-4152-8262-152b4488c01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Add    </value>
      <webElementGuid>4cc42517-e6e4-4824-8aca-6f0bb13cb679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addInvoice&quot;)</value>
      <webElementGuid>46fd45ff-f4ec-483b-952c-870da1030359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addInvoice']</value>
      <webElementGuid>2f05e681-c0ed-46cd-a05b-0edfca5e0f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-addInvoice']/button</value>
      <webElementGuid>fcdd267a-cf11-4f83-8327-a47134afc7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Upload Listing'])[1]/following::button[1]</value>
      <webElementGuid>5c1921be-9f0e-42b6-ac4b-8cdd0186b950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
      <webElementGuid>edb1bdad-62b8-4b2f-91e8-db10eb114458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panelMainVg'])[1]/preceding::button[1]</value>
      <webElementGuid>46d6647d-f303-4da2-8d57-73bb2352c5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button</value>
      <webElementGuid>eed09b75-b068-49cc-8875-ef23c64a5f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addInvoice' and @name = 'addInvoice' and @type = 'button' and (text() = '    Add    ' or . = '    Add    ')]</value>
      <webElementGuid>16920275-c407-4621-8cdd-f508bd374d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
