<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_browse</name>
   <tag></tag>
   <elementGuidId>86d87de7-c800-4848-9d02-5da40f59cf2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='excelCsvUpload-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#excelCsvUpload-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71eaa23c-e367-4ccf-af62-57b2ac1c42ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28bd8797-5568-4a55-8c6b-9106f38f7bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngf-select</name>
      <type>Main</type>
      <value>upload($files, $invalidFiles)</value>
      <webElementGuid>87b81a86-e829-4ab7-85cc-f79751d8f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngf-accept</name>
      <type>Main</type>
      <value>component.filePattern</value>
      <webElementGuid>9083cdff-0730-482f-9bcb-ef41ca843bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngf-multiple</name>
      <type>Main</type>
      <value>component.multiple</value>
      <webElementGuid>09463cc4-547a-47cb-b288-2b3a4f2afcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-link fileSelector__button ng-binding</value>
      <webElementGuid>b92bbcb6-1841-4494-808e-f1c81d61540d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>browse</value>
      <webElementGuid>619833af-364c-4b44-9a79-9d19b3c2fd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>excelCsvUpload</value>
      <webElementGuid>4b4f466f-59e6-4258-8c02-947ea880bd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>excelCsvUpload-button</value>
      <webElementGuid>f4e670e3-6b1b-49d3-b39b-be8edaad3526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> browse </value>
      <webElementGuid>0f900094-c1e6-4087-8813-d050b3776eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;excelCsvUpload-button&quot;)</value>
      <webElementGuid>a5ced961-9dcb-47bf-bd9e-fefc2a4d37eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='excelCsvUpload-button']</value>
      <webElementGuid>76e4af1f-a7a8-4258-9360-8bf97db1ee50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='excelCsvUpload']/button</value>
      <webElementGuid>1dd8c5ec-2b03-4d23-b30a-78b2696c80e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::button[1]</value>
      <webElementGuid>0702e9dd-d827-4343-8992-cc93eae6ce07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum allowed file size (each file): MB'])[1]/preceding::button[1]</value>
      <webElementGuid>ccb74261-bf6b-47d9-a39f-08316466247b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Drag/Drop is not supported for this browser'])[1]/preceding::button[1]</value>
      <webElementGuid>6b9be477-c932-43f6-8716-3bde46eba704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='browse']/parent::*</value>
      <webElementGuid>04c7a76a-a5b6-4f42-83ed-5a46c128a083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>d8f31abc-4178-4ff5-a42c-5abf1910bdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'excelCsvUpload-button' and (text() = ' browse ' or . = ' browse ')]</value>
      <webElementGuid>4db322d6-c9f5-4961-a9c9-fc3b7651e5c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
