<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Kratos User Email_confirmEmail</name>
   <tag></tag>
   <elementGuidId>8fdd572f-9b5e-4a27-8982-6b541e91a695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14d014d5-f77d-4d6c-bb48-f071ab2f1de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bac1c2c1-8451-4a6b-a36f-54c436509646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-empty ng-valid-email ng-valid-json-schema ng-invalid ng-invalid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-invalid-custom-error ng-dirty</value>
      <webElementGuid>c7e0bac2-e599-44ce-8baf-a57be6c5da75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>bee97076-f5fe-4ebe-a7be-176d1e28967a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmEmail</value>
      <webElementGuid>b53b12ba-b0ab-487e-8401-1027447db2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>input.model</value>
      <webElementGuid>63db1063-2391-4144-bdf4-8dd892cee6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>inputChanged()</value>
      <webElementGuid>aafc0ce3-225d-40db-9e1a-79e0aa9b59cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ allowInvalid: true }</value>
      <webElementGuid>f9dca2e7-49f6-4212-a9f6-f0006307465a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>isRequired(component)</value>
      <webElementGuid>8fce6aee-1a1f-4436-bf95-0f56ff66669c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>component.disabled</value>
      <webElementGuid>9e474561-fd1e-4c09-8f51-8d836dc46a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>onKeyDownHandler($event)</value>
      <webElementGuid>f91b3610-a832-48f5-837b-64bd280c6beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-step</name>
      <type>Main</type>
      <value>{{ component.validate.step }}</value>
      <webElementGuid>b6612bcc-7542-44ec-b1d8-d876e06fec8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-placeholder</name>
      <type>Main</type>
      <value>{{ component.placeholder }}</value>
      <webElementGuid>e64603c9-1b41-4825-8cf5-f6e57c9054c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>hasFocus(true)</value>
      <webElementGuid>a316070f-f96d-4567-a277-57b67ec4f038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>hasFocus(false)</value>
      <webElementGuid>24fadc87-2550-4ac8-86da-e638288b6fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom-validator</name>
      <type>Main</type>
      <value>component.validate.custom</value>
      <webElementGuid>f6f4dde1-2c43-417e-afec-8d7aa3b22d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d0df0f8-e96d-4dd2-a6db-d358b7968936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-aria-describedby</name>
      <type>Main</type>
      <value>{{ ariaDescribedby }}</value>
      <webElementGuid>c71f22b4-3368-40d2-b65f-509db8160331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Confirm Kratos User Email</value>
      <webElementGuid>cdf06209-52cf-4326-bfd1-4342a460fff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48a36acd-97e4-4483-b560-efe811de5363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e3832bb6-a38d-4360-927b-eace8f1719a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>confirmEmail-errors</value>
      <webElementGuid>519a9835-5ddf-4237-abcb-2f849dd69b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmEmail&quot;)</value>
      <webElementGuid>dba120ab-aa7a-437a-8719-c4c396809f5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmEmail']</value>
      <webElementGuid>6e4363d3-e665-43eb-b409-2b847b8d7386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-group-confirmEmail']/div/div/input</value>
      <webElementGuid>af704c43-3807-403f-83a9-e2f5d19f0f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>7f0a7536-3b96-417c-8226-ee44f3f9fcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'confirmEmail' and @name = 'confirmEmail']</value>
      <webElementGuid>19f9f9ee-66fb-4741-bd2d-fd0965e4e5cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
