<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KratosAdminMaker</name>
   <tag></tag>
   <elementGuidId>0b51792a-2d9e-43c4-8ef2-ad5047551db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-select-choices-row-1-1 > span.ui-select-choices-row-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-select-choices-row-1-1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9da0d934-00e2-474d-9b65-f881379eac8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-select-choices-row-inner</value>
      <webElementGuid>d32b1573-cffe-4578-9bcb-42db1f57ec21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  KratosAdminMaker  </value>
      <webElementGuid>d5a3ffa9-942f-48a1-8985-9861fb8ae183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-select-choices-row-1-1&quot;)/span[@class=&quot;ui-select-choices-row-inner&quot;]</value>
      <webElementGuid>84da392d-9898-40f6-9456-869421d7f55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-select-choices-row-1-1']/span</value>
      <webElementGuid>fa9fa9fd-cbca-483b-a972-348eb9f15064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='StaffSCF'])[1]/following::span[1]</value>
      <webElementGuid>98e4bfb1-f8e5-40ed-a9da-15e2e270f488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::span[6]</value>
      <webElementGuid>f96b8f14-1b4d-433a-a7bb-281e736a875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KratosAdminChecker'])[1]/preceding::span[2]</value>
      <webElementGuid>8e7e9e69-ebab-48b6-a2a6-c8c5a3ea957d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>06a7e961-c70f-4dd5-aa3a-8592c740725b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  KratosAdminMaker  ' or . = '  KratosAdminMaker  ')]</value>
      <webElementGuid>66dc827c-6820-4745-a779-43c468823aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
